services:
  - type: web
    name: miniurl-backend
    runtime: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: ./backend/miniURL
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_DRIVER
        value: org.postgresql.Driver
      - key: HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
